### ISSUE TITLE
Stopped Search 

### ISSUE THREAD

**Issue by Chris-EduardDunareanu** [TobiasPankner/Teams-Auto-Joiner#77] opened 2021-02-23 11:57 UTC
if you have activated leave_threshold_number and the meeting gets closed by the owner, the programm still thinks you are in a meeting and the programm doesnt look for new meeting.

**Comment by TobiasPankner** [comment] 2021-02-23 17:44
So the bot doesn't leave the meeting because it's closed by the owner before (and after that doesn't join anything again)?

**Comment by TheBroGamersTv** [comment] 2021-02-23 19:29
Yes

**Comment by ThunderArmy** [comment] 2021-03-02 13:33
I've got the same issue, if the meeting is termined by the owner it won't join any new meetings

**Comment by IMMANUEL44** [comment] 2021-09-13 09:08
Yes same issue here too...the script crashes and ends basically

**Comment by AP-XD** [comment] 2022-01-24 04:52
> I've got the same issue, if the meeting is termined by the owner it won't join any new meetings

Yes same issue here too.
So what I did was I saw the error it was giving was
"Failed to open meeting member page"
So I checked the condition before it.
` if "pause_search" in config and config['pause_search'] and current_meeting is not None:`
and since current_meeting meeting is not None, it basically thinks u are still in a meeting and the search stays paused,
so when that error gets triggered I set 
`current_meeting=None`
This fixes it for me.
![image](https://user-images.githubusercontent.com/63340491/150723685-ffff389b-8975-421d-84a7-c127113d6a66.png)

![image](https://user-images.githubusercontent.com/63340491/150723285-952ad218-d095-4485-8800-bb8a5bf80455.png)

**Comment by TobiasPankner** [comment] 2022-01-24 05:54
This is not a permanent fix as it introduces other problems.  
Can you describe to me what happens to trigger the problems you are describing? I cannot reproduce it

**Comment by AP-XD** [comment] 2022-01-24 06:06
> This is not a permanent fix as it introduces other problems. Can you describe to me what happens in the browser at the time of error?

Nothing happens it stays in the teams channel page.

**Comment by TobiasPankner** [comment] 2022-01-24 06:19
Okay, but what happens before that? Is the meeting cancelled and ypu are kicked out?

**Comment by AP-XD** [comment] 2022-01-24 06:59
> Okay, but what happens before that? Is the meeting cancelled and ypu are kicked out?

No the meeting is terminated by the host before the number of members in meeting reaches the leave threshold.

**Comment by TobiasPankner** [comment] 2022-01-24 07:41
I just pushed an update, please inform me if this fix works. Thank you

**Comment by AP-XD** [comment] 2022-01-24 12:32
> I just pushed an update, please inform me if this fix works. Thank you

![image](https://user-images.githubusercontent.com/63340491/150783408-c56fe49a-551e-415a-ae7f-0b7fcaa7c260.png)
Working Perfectly Thanks!!!!
@TobiasPankner

**Closed** 2022-01-24 12:43 UTC
