### ISSUE TITLE
Fails to find the number of participants

### ISSUE THREAD

**Issue by kushagrag2ae** [TobiasPankner/Teams-Auto-Joiner#125] opened 2021-08-02 05:42 UTC
the program is barely able to find or get the number of participants. not able to use the threshold participants or last person features because of it.

![image](https://user-images.githubusercontent.com/57147719/127809177-29f44163-0e94-48e3-8b7e-c35c1b47e103.png)

![image](https://user-images.githubusercontent.com/57147719/127809367-b8b572c3-b415-4a48-a301-29157028d029.png)

**Desktop (please complete the following information):**
 - OS: kali linux
 - Browser: google chrome
 - Version: Google Chrome 92.0.4515.107 

i just need to get this solved so that i can use the last person feature easily because right now it is not working do the inability of the code to get the number of members. it get the correct number of participants for about 1 or 2 times out of the 10 times it checks

it further causes problems because then it joins random meetings with just 2 people sitting in it and then because it is not able to fetch the number of participants it doesn't realize it until some new meeting starts

**Comment by TobiasPankner** [comment] 2021-08-03 15:31
How does this look in the browser? Does the meeting member screen open?

**Comment by kushagrag2ae** [comment] 2021-08-03 15:41
yes this is another thing, so the first time it would open the members list and still fail to fetch the number of participants. then when the next time it tries to open the members list after looking for a new meeting it would close the already opened members list and now either ways it is not able to fetch the number of participants

**Comment by DishantX** [comment] 2021-08-05 08:13
The same issue still occurs with me. It never left the meeting.

**Comment by gauravreddy08** [comment] 2021-08-06 07:30
I have the same issue. Is there any fix yet ?

**Comment by TobiasPankner** [comment] 2021-08-06 08:24
I will try and fix this today.

**Comment by gauravreddy08** [comment] 2021-08-06 08:39
> I will try and fix this today.

Hope this might help !!

<img width="524" alt="Screenshot 2021-08-06 at 2 08 33 PM" src="https://user-images.githubusercontent.com/57211163/128482707-a99a4201-9f74-4001-8535-6121717e0462.png">

**Comment by TobiasPankner** [comment] 2021-08-06 14:06
Can you please post your config file @gauravreddy08 @DishantX

**Comment by gauravreddy08** [comment] 2021-08-06 14:26
```
{
  

  "run_at_time": "",

  "meeting_mode": 2,
  "organisation_num" : 0,
  "random_delay": true,
  "check_interval": 5,

  "join_message": "",

  "auto_leave_after_min": -1,
  "leave_if_last": true,
  "leave_threshold_number": "15",
  "leave_threshold_percentage": "",
  "pause_search": true,

  "headless" : false,
  "mute_audio": true,
  "chrome_type": "google-chrome",

  "blacklist": [],
  "blacklist_meeting_re": "",
  "discord_webhook_url" : "https://discord.com/api/webhooks/873089242669146112/2m1lWVI0kPYkavAOX7fF4ZSjB_0edGW5_iPcDbbdUoEdYz2E9-lODNlMpja2hZL-r6oC"
}

```

**Comment by TobiasPankner** [comment] 2021-08-06 14:26
This was an issue when pause_search is true. Thank you for bringing this to my attention.
Should be fixed with commit 90300a4

**Closed by TobiasPankner** 2021-08-06 14:26 UTC

**Comment by gauravreddy08** [comment] 2021-08-06 14:27
> This was an issue when pause_search is true. Thank you for bringing this to my attention.
> Should be fixed with commit 90300a4

Cool, Thanks !!

**Comment by DishantX** [comment] 2021-08-20 03:11
The error still exists to me

**Comment by TobiasPankner** [comment] 2021-08-20 04:21
Please post the console log @DishantX

**Comment by DishantX** [comment] 2021-08-20 07:13
Same I guess
`[8268:10684:0820/124055.950:ERROR:webrtc_video_engine.cc(3414)] Absent receive stream; ignoring clearing encoded frame sink for ssrc 0
Failed to close meeting member page, this might result in an error on next search

[12:41:10] Meeting search is paused because you are still in a meeting
Failed to open meeting member page

[12:41:22] Meeting search is paused because you are still in a meeting
Failed to open meeting member page
[5496:11396:0820/124128.376:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled`

**Comment by DishantX** [comment] 2021-08-20 07:16
![image](https://user-images.githubusercontent.com/71291013/130195071-da300593-3198-4bd3-8d28-d2e576187849.png)

**Comment by TobiasPankner** [comment] 2021-08-20 11:54
Okay, and what is going on in the browser?

**Comment by DishantX** [comment] 2021-08-20 13:47
The browser opens the member page. But after that code says - Failed to open meeting member page. Ironic!

**Comment by DishantX** [comment] 2021-08-20 13:49
The browser opens the meeting page. But after that code says - Failed to open member meeting page. Ironic!

**Comment by TobiasPankner** [comment] 2021-08-20 14:03
The problem is that it can't close the meeting member page. Is anything in front of the buttons like a notification?

**Comment by TobiasPankner** [comment] 2021-08-20 14:07
And can you please post your config?

**Comment by DishantX** [comment] 2021-08-20 14:13
```
{
  "email": "",
  "password": "",

  "run_at_time": "",

  "meeting_mode": 1,
  "organisation_num" : -1,
  "random_delay": false,
  "check_interval": 10,

  "join_message": "",

  "auto_leave_after_min": -1,
  "leave_if_last": true,
  "leave_threshold_number": 10,
  "leave_threshold_percentage": -1,
  "pause_search": true,

  "headless" : false,
  "mute_audio": false,
  "chrome_type": "google-chrome",

  "blacklist": [
    {
      "team_name": "Example Team 1",
      "channel_names": [
        "First Channel to blacklist in this team",
        "Second Channel to blacklist"
      ]
    },
     {
      "team_name": "Blacklist whole team",
      "channel_names": [
      ]
    }
  ],
  "blacklist_meeting_re": "",

  "discord_webhook_url" : "https://discord.com/api/webhooks/854912515457024040/Bz4FwtQbpd4gRrYUWrsB2MFZA__uznNNFp3DZlhHtshLjjEyjyI7Js5yoHaNg0rC71xJ"
}
```

**Comment by TobiasPankner** [comment] 2021-08-20 14:20
I cannot reproduce the error, is this happening everytime for you?

**Comment by DishantX** [comment] 2021-08-20 14:21
> Is anything in front of the buttons like a notification?

Nope

**Comment by DishantX** [comment] 2021-08-20 14:23
It happens every time

**Comment by TobiasPankner** [comment] 2021-08-20 14:24
Weird, can you take a video of this happening? And a temporary fix is to switch pause_search to false

**Comment by TobiasPankner** [comment] 2021-08-20 14:26
Further comments in the new issue #133 please

**Comment by DishantX** [comment] 2021-08-20 14:27
I will try to share a video after a new meeting is held

**Comment by TobiasPankner** [comment] 2021-08-20 14:28
Perfect, thank you. Either send the video to my email or post a link in the #133 issue
